name: Zwooko

on: [pull_request_target, issues]

jobs:
  zwooko:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for help us out with our project!"
        pr-message: "We have received the pull request and will review it ASAP! :-)"
